apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
  - ../../base

components:
  - ../../components/components-serving
  - ../../components/config-access-everyone
  - ../../components/model-server-pod-sizes
