apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/openshift-ai/instance/overlays/minimal?ref=v0.17
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/openshift-ai/operator/overlays/stable?ref=v0.17

patches:
  - target:
      kind: ConfigMap
      name: notebook-controller-culler-config
    path: patch-culler.yaml
    # patch: |-
    #   - op: replace
    #     path: /data
    #     value:
    #       CULL_IDLE_TIME: "60"
    #       ENABLE_CULLING: "true"
    #       IDLENESS_CHECK_PERIOD: "1"
    