apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../modules/cluster-configs/login/overlays/htpasswd

  - ../../modules/operators/rhods-operator/instance/overlays/minimal
  - ../../modules/operators/rhods-operator/operator/overlays/stable-2.13
